=== 2Fastt/Validacion-XML-DTD/DTD 2/Ejercicio 3/aeropuertoo.dtd
<!ELEMENT Aeropuerto (nombre, panel_fecha, vuelo+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT panel_fecha (#PCDATA)>
<!ELEMENT vuelo (origen, destino, hora_salida, hora_llegada, diario?)>
<!ATTLIST vuelo codigo ID #REQUIRED estado (C | E | R) "E">
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>
<!ELEMENT diario EMPTY>

=== 2Fastt/Validacion-XML-DTD/DTD 2/Ejercicio 3/aeropuerto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Aeropuerto SYSTEM "aeropuertoo.dtd">

<Aeropuerto>
    <nombre>Aeropuerto JFK</nombre>
    <panel_fecha>20/12/2013</panel_fecha>

    <vuelo codigo="v22" estado="R">
        <diario>SI</diario>
        <origen>New York</origen>
        <destino>Chicago</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>11:30</hora_llegada>
    </vuelo>
