<?xml version="1.0" encoding="UTF-8">
<!DOCTYPE reyesEspa単oles [
    <!ELEMENT reyesEspa単oles (rey*, reina*)>
    <!ELEMENT rey (nombre, padre, madre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT padre (#PCDATA)>
    <!ELEMENT madre (#PCDATA)>
]>
<reyesEspa単oles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    <reina>
        <nombre>Juana la Loca</nombre>
        <padre>Fernando el Catolico</padre>
        <madre>Isabel la Catolica</madre>
    </reina>
    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe el Hermoso</padre>
        <madre>Juana la Loca<madre>
    </rey>
</reyesEspa単oles>
